#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod1    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-Escape quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close
hc keybind $Mod-0 spawn slock
hc keybind $Mod-Shift-0 spawn ~/bin/suspend.sh

hc keybind $Mod-Return spawn st
hc keybind $Mod-Shift-Return spawn termite
# hc keybind $Mod-d spawn rofi -show drun -yoffset 80
hc keybind $Mod-d spawn dmenu_run -m 0 -fn "Iosevka Term:weight=medium:size=8" -nb "#3a3a3a" -nf "#d0d0d0" -sb "#3a3a3a" -sf "#af5f5f" -p "dmenu"
# hc keybind $Mod-q chain . emit_hook focus_frame . spawn rofi -show run -yoffset 80


# Brightness and volume controls
hc keybind XF86AudioLowerVolume spawn volumeControl.sh down
hc keybind XF86AudioRaiseVolume spawn volumeControl.sh up
hc keybind XF86AudioMute spawn volumeControl.sh mute
hc keybind XF86MonBrightnessUp spawn brightnessControl.sh up
hc keybind XF86MonBrightnessDown spawn brightnessControl.sh down
hc keybind XF86AudioNext spawn playerctl next
hc keybind XF86AudioPrev spawn playerctl previous
hc keybind XF86AudioPlay spawn playerctl play-pause

# basic movement
# focusing clients
#hc keybind $Mod-Left  focus left
#hc keybind $Mod-Down  focus down
#hc keybind $Mod-Up    focus up
#hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
#hc keybind $Mod-Shift-Left  shift left
#hc keybind $Mod-Shift-Down  shift down
#hc keybind $Mod-Shift-Up    shift up
#hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.025
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
#hc keybind $Mod-Control-Left    resize left +$resizestep
#hc keybind $Mod-Control-Down    resize down +$resizestep
#hc keybind $Mod-Control-Up      resize up +$resizestep
#hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..5} )
tag_keys=( {1..5} )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-Shift-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# Change gaps
hc keybind $Mod-g cycle_value frame_gap 7 0

# Show hide frames
hc keybind $Mod-n cycle_value always_show_frame 0 1
hc keybind $Mod-m cycle_value frame_normal_opacity 0 40



# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#5f8787'
hc set frame_border_normal_color '#5f8787'
hc set frame_bg_normal_color '[0]#5f8787'
hc set frame_bg_active_color '[0]#DADADA'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_active_opacity 0
hc set frame_normal_opacity 0
hc set frame_transparent_width 0
hc set frame_gap 5

hc attr theme.active.color '#DADADA'
hc attr theme.normal.color '#DADADA'
hc attr theme.urgent.color '#0087af'
hc attr theme.inner_width 2
hc attr theme.inner_color '#DADADA'
hc attr theme.border_width 5
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 2
hc attr theme.floating.outer_color '#DADADA'
hc attr theme.active.inner_color '#af5f5f'
hc attr theme.active.outer_color '#af5f5f'
hc attr theme.background_color '[0]#DADADA'

hc set window_gap 5
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1
hc set focus_stealing_prevention 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
#hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' manage=on focus=on pseudotile=on
#hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

#hc set tree_style '╾│ ├└╼─┐'
#hc set tree_style "-| |'--"
hc set tree_style '╾│ ├╰╼─╮'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors


hsetroot -solid '#626262'
# feh --bg-scale '/home/ossifrage/Pictures/Wallpapers/really_minimal/unsorted/abstract.png' &
compton -b &
numlockx on &
# dunst -c ~/.config/dunst/dunstrc &
# twmnd &
killall -q redshift; sleep 3 && redshift -c ~/.config/redshift.conf &
# mpd &
# flashfocus &


# find the panel
panel=~/.config/herbstluftwm/launch.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
		hc pad $monitor 22 0 0 0
done
