#! /bin/sh

gap=10
PANEL_HEIGHT=22
export gap
export PANEL_HEIGHT

bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT-$gap))
#bspc config top_monocle_padding $gap

## Various settings

# Settings for manual splitting
bspc config split_ratio          0.66
bspc config gapless_monocle      true
bspc config borderless_monocle	 true
bspc config single_monocle	 true
# bspc config paddingless_monocle  false

# bspc config ignore_ewmh_focus      true
# bspc config initial_polarity second_child

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

# bspc config honor_size_hints true


## Color settings
bspc config focused_border_color  "#af5f5f"
bspc config normal_border_color   "#DADADA"
#bspc config urgent_border_color   "#d95468"
bspc config presel_feedback_color "#DADADA"
bspc config presel_feedback true
#bspc config normal_frame_opacity 1
bspc config border_width 3


## Focus follows mouse cursor
bspc config focus_follows_pointer true

## Workspace names
# bspc monitor -d I II III IV V VI VII VIII
# bspc monitor -d i ii iii iv v vi vii viii
# bspc monitor -d One Two Three Four Five Six Seven Eight Nine Ten
# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d • • • • • • • • • •
# bspc monitor -d I II III IV V VI
bspc monitor -d 001 010 011 100 101

## This creates and names desktops for multiple monitors.
# workspaces_multimonitor &


## Window rules
# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a gcolor2 state=floating center=true
#bspc rule -a Lxappearance floating=true center=true
#bspc rule -a conky sticky=on manage=off lower=on
bspc rule -a polybar layer=above
bspc rule -a '*:Firefox' private=on desktop=1 state=tiled
#bspc rule -a libreoffice state=tiled
#bspc rule -a '*:libreofficedev' state=tiled
#bspc rule -a '*:soffice' state=tiled
bspc rule -a open state=floating center=false
bspc rule -a 'Save file to*' state=floating center=false
bspc rule -a 'Save' state=floating center=true
#bspc rule -a URxvt state=floating center=false
#bspc rule -a st-256color -o state=floating center=false
#bspc rule -a URxvt:ncmpcpp desktop=^4 state=pseudotiled
#bspc rule -a URxvt:cava desktop=^4 state-pseudotiled
#bspc rule -a termite:ncmpcpp desktop=^4 state=pseudotiled
#bspc rule -a termite:cava desktop=^4 state=pseudotiled
bspc rule -a slop state=floating center=false
bspc rule -a Spotify monocle=on
bspc desktop 1 --layout monocle
# bspc desktop II --layout monocle

# hoping for floating launcher support sith urxvt but needs work
bspc rule -a URxvt:stick state=floating sticky=on center
bspc rule -a URxvt:stick1 state=floating sticky=on
bspc rule -a URxvt:stick2 state=floating sticky=on
bspc rule -a URxvt:float state=floating


## Autostart apps
# Keybindings from sxhkd
sxhkd -c ~/.config/bspwm/sxhkdrc &

# Notification service
# daemon started by systemd
# dunst -c ~/.config/dunst/dunstrc &
# twmnd &

# Numlock
numlockx on &

# Polkit agent
# run from terminal if necessary
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# ???
#fix_xcursor &
#xsetroot -cursor_name Chameleon-Pearl-Small-0.5 &
#fix_xcursor &
xsetroot -cursor_name left_ptr &

# Redshift
killall redshift; sleep 3 && redshift -c ~/.config/redshift.conf &

# Polybar(s)
$HOME/.config/bspwm/launch.sh bspwm &

# Hide mousecursor when inactive
unclutter -root &

## Pywal
# restore the colorscheme
# wal -R

# Wallpaper and Compositor
#nitrogen --restore; sleep 1; compton --dbus &
# feh --bg-scale '/home/ossifrage/Pictures/Wallpapers/really_minimal/aleks-dahlberg-274644-unsplash.jpg'; sleep 1; compton -b &
hsetroot -solid '#626262'

# Pulseaudio
#pulseaudio -k &
#pulseaudio --start &


# Spotifyd
#/usr/bin/spotifyd &

# 2bspwm
#~/bin/2bspwm &

# blur-me
#~/bin/blurme &

# flashfocus
pkill flashfocus &
flashfocus &
